language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2

install:
  - composer update --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/coverage-check coverage.xml 100
  - vendor/bin/phpcs -np --colors
  - vendor/bin/phpstan analyse

after_sscript:
  - bash <(curl -s https://codecov.io/bash)

