FactorioItemBrowser\ExportData\Entity\Icon\Color:
  exclusion_policy: all
  properties:
    red:
      type: float
    green:
      type: float
    blue:
      type: float
    alpha:
      type: float
