FactorioItemBrowser\ExportData\Entity\Recipe:
  exclusion_policy: all
  properties:
    name:
      type: string
    labels:
      type: FactorioItemBrowser\ExportData\Collection\TranslationDictionary
    descriptions:
      type: FactorioItemBrowser\ExportData\Collection\TranslationDictionary
    mode:
      type: string
    ingredients:
      type: array<FactorioItemBrowser\ExportData\Entity\Recipe\Ingredient>
    products:
      type: array<FactorioItemBrowser\ExportData\Entity\Recipe\Product>
    craftingTime:
      type: float
    craftingCategory:
      type: string
    iconId:
      type: string
