FactorioItemBorwser\ExportData\Entity\Mod:
  access_type: public_method
  exclusion_policy: all
  properties:
    name:
      type: string
    titels:
      type: FactorioItemBorwser\ExportData\Entity\LocalisedString
    descriptions:
      type: FactorioItemBorwser\ExportData\Entity\LocalisedString
    author:
      type: string
    version:
      type: string
    thumbnailHash:
      type: string
