FactorioItemBrowser\ExportData\Entity\Mod:
  exclusion_policy: all
  properties:
    name:
      type: string
    titles:
      type: FactorioItemBrowser\ExportData\Collection\TranslationDictionary
    descriptions:
      type: FactorioItemBrowser\ExportData\Collection\TranslationDictionary
    author:
      type: string
    version:
      type: string
    thumbnailId:
      type: string
