FactorioItemBrowser\ExportData\Entity\Recipe\Product:
  exclusion_policy: all
  properties:
    type:
      type: string
    name:
      type: string
    amountMin:
      type: float
    amountMax:
      type: float
    probability:
      type: float
