FactorioItemBrowser\ExportData\Entity\Item:
  exclusion_policy: all
  properties:
    type:
      type: string
    name:
      type: string
    labels:
      type: FactorioItemBrowser\ExportData\Collection\TranslationDictionary
    descriptions:
      type: FactorioItemBrowser\ExportData\Collection\TranslationDictionary
    iconId:
      type: string
