FactorioItemBrowser\ExportData\Entity\Icon\Layer:
  access_type: public_method
  exclusion_policy: all
  properties:
    fileName:
      type: string
    tint:
      type: FactorioItemBrowser\ExportData\Entity\Icon\Color
    offsetX:
      type: integer
    offsetY:
      type: integer
    scale:
      type: float
