FactorioItemBrowser\ExportData\Entity\Machine:
  exclusion_policy: all
  properties:
    name:
      type: string
    labels:
      type: FactorioItemBrowser\ExportData\Collection\Translations
    descriptions:
      type: FactorioItemBrowser\ExportData\Collection\Translations
    craftingCategories:
      type: array<string>
    craftingSpeed:
      type: float
    numberOfItemSlots:
      type: integer
    numberOfFluidInputSlots:
      type: integer
    numberOfFluidOutputSlots:
      type: integer
    numberOfModuleSlots:
      type: integer
    energyUsage:
      type: float
    energyUsageUnit:
      type: string
    iconId:
      type: string
